plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    // Springboot web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Springboot test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'


    // h2
    runtimeOnly 'com.h2database:h2'

    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // 테스트를 위한 롬복
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.projectlombok:lombok'

    // 자바 JWT 라이브러리
    implementation 'io.jsonwebtoken:jjwt:0.9.1'

    // XML 문서와 Java 객체 간 매핑 자동화
    implementation 'javax.xml.bind:jaxb-api:2.3.1'

}

test {
    useJUnitPlatform()
}